### ISSUE TITLE
 'ios' file not found

### ISSUE THREAD

**Issue by Xiaojieqiu** [Lioscro/fbgbp#7]
In case anyone who may confront this error. 

When install this package on macOS, I got the following  warning/error: 
```
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]

fbgbp/grid_belief_propagation.cpp:738:10: fatal error: 'ios' file not found

```
The solution is: 
CFLAGS='-stdlib=libc++' python3 setup.py install

**Comment by Lioscro** [comment]
This should be fixed in version `0.0.10`
